---
- name: ensure lvm2 is installed
  shell: >
    rpm -q lvm2 || yum install -y lvm2 && echo yes
  args:
    warn: false
  register: pkg_installed
  changed_when: pkg_installed.stdout == 'yes'
  tags:
    - pkgs

- name: "checking if /dev/{{ host_device }} exist"
  parted:
    device: /dev/{{ host_device }}
    unit: MiB
  register: device_info
  ignore_errors: yes
  changed_when: device_info.failed|bool

- name: fail if host_device not found
  fail:
    msg: |
       Could not find the device /dev/{{ host_device }}
       please ensure the variable host_device is set to the device
       you want to use.
  when: device_info.failed|bool

- name: get volume group name
  set_fact:
    vg_name_check: "LVM2_VG_NAME={{ vg_name }}"
    vg_not_on_pv: ""
    vg_not_exist: ""
    vg_exist: ""

- name: check if the {{ vg_name }} is on the device /dev/{{ host_device }}
  shell: |
    set -o pipefail &&  pvs -o vg_name,pv_name --noheadings --nameprefixes --unquoted|awk '/{{ host_device }}/ {print $1}'
  args:
   executable: /bin/bash
  register: pvs_info
  changed_when: pvs_info.stdout != vg_name_check

- name: check pvs
  set_fact:
    vg_not_on_pv: "{{ true if pvs_info.stdout != vg_name_check else false }}"

- name: check if the {{ vg_name }} exist
  shell: |
    set -o pipefail && vgs -o vg_name,pv_name --noheadings --nameprefixes --unquoted| awk '/{{ vg_name }}/ {print $1}'
  register: vg_info
  changed_when: vg_info.stdout != vg_name_check
  args:
    executable: /bin/bash

- name: chcking volume group info
  set_fact:
    vg_not_exist: "{{ true if vg_info.stdout != vg_name_check else false }}"

- name: checking volumegoup info
  set_fact:
    vg_exist: "{{ true if vg_info.stdout == vg_name_check else false }}"

- name: fail when device does not exisit
  fail:
    msg: |
      The {{ vg_name }} exist but not on device /dev/{{ host_device }}
      please resolve and rerun the play. Either update the host_device variable or
      change the vg_name variable value to something else.
  when: vg_exist and vg_not_on_pv


- name: create volume group
  set_fact:
    create_vg: "{{ true if vg_not_exist and vg_not_on_pv else false }}"

- debug:
    msg: "{{ vg_name }} will be created on /dev/{{ host_device }}"
  when: create_vg|bool