---
- name: ensure lvm2 is installed
  package:
    name: lvm2

- name: "checking if /dev/{{ host_device }} exist"
  parted: 
    device: /dev/{{ host_device }} 
    unit: MiB
  register: device_info

- debug:
    msg: "{{ device_info }}"


- name: check if /dev/{{ host_device }} has a formated partition
  shell: "pvs | awk '\//dev/{{ host_device }}\/ {print $1}'"
  args:
   executable: /bin/bash
  register: pvs_info

- debug:
    msg: "{{ pvs_info }}"


- name: check which vg is assigned to /dev/{{ host_device }}
  shell: "pvs | awk '\//dev/{{ host_device }}\/ {print $2}'"
  args:
   executable: /bin/bash
  register: vgs_info

- debug:
    msg: "{{ vgs_info }}"


- set_fact:
    create_vg: "{{ true if device_info.stdout != '' and vgs_info.stdout == '' and pvs_info.stdout == '' else false }}"

- set_fact:
    current_vg: "{{ pvs_info.stdout if pvs_info.stdout != '' else 'no_vg' }}"

- fail:
    msg: |
        The device /dev/{{ host_device }} already has a volume group name {{ current_vg }}
        that does not match the given expected volume group name {{ vg_name }}
        either change the value of host_device or remove the volume group {{ current_vg }}
        Example:   
                   sudo vgremove {{ current_vg }} -ff -y
                   sudo pvremove /dev/{{ host_device }} -ff -y
  when: not create_vg|bool